export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'

export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const USER_TOPSELLERS_LIST_REQUEST = 'USER_TOPSELLERS_LIST_REQUEST'
export const USER_TOPSELLERS_LIST_SUCCESS = 'USER_TOPSELLERS_LIST_SUCCESS'
export const USER_TOPSELLERS_LIST_FAIL = 'USER_TOPSELLERS_LIST_FAIL'

export const USER_SELLERS_LIST_REQUEST = 'USER_SELLERS_LIST_REQUEST'
export const USER_SELLERS_LIST_SUCCESS = 'USER_SELLERS_LIST_SUCCESS'
export const USER_SELLERS_LIST_FAIL = 'USER_SELLERS_LIST_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_RESET = 'USER_DELETE_RESET'

export const USER_ADDRESS_MAP_CONFIRM = 'USER_ADDRESS_MAP_CONFIRM'

export const USER_UPGRADE_REQUEST = 'USER_UPGRADE_REQUEST'
export const USER_UPGRADE_SUCCESS = 'USER_UPGRADE_SUCCESS'
export const USER_UPGRADE_FAIL    = 'USER_UPGRADE_FAIL'

export const USER_PASSWORDRECOVERY_REQUEST = "USER_PASSWORDRECOVERY_REQUEST"
export const USER_PASSWORDRECOVERY_SUCCESS = "USER_PASSWORDRECOVERY_SUCCESS"
export const USER_PASSWORDRECOVERY_FAIL    = "USER_PASSWORDRECOVERY_FAIL"

export const USER_PASSWORD_REPLACEMENT_REQUEST = "USER_PASSWORD_REPLACEMENT_REQUEST"
export const USER_PASSWORD_REPLACEMENT_SUCCESS = "USER_PASSWORD_REPLACEMENT_SUCCESS"
export const USER_PASSWORD_REPLACEMENT_FAIL    = "USER_PASSWORD_REPLACEMENT_FAIL"

export const USER_NEWSLETTER_REQUEST = "USER_NEWSLETTER_REQUEST"
export const USER_NEWSLETTER_SUCCESS = "USER_NEWSLETTER_SUCCESS"
export const USER_NEWSLETTER_FAIL    = "USER_NEWSLETTER_FAIL"

export const USER_NEWSLETTER_VERIFICATION_REQUEST = "USER_NEWSLETTER_VERIFICATION_REQUEST"
export const USER_NEWSLETTER_VERIFICATION_SUCCESS = "USER_NEWSLETTER_VERIFICATION_SUCCESS"
export const USER_NEWSLETTER_VERIFICATION_FAIL    = "USER_NEWSLETTER_VERIFICATION_FAIL"

export const USER_NEWSLETTER_UPDATE_REQUEST = "USER_NEWSLETTER_UPDATE_REQUEST"
export const USER_NEWSLETTER_UPDATE_SUCCESS = "USER_NEWSLETTER_UPDATE_SUCCESS"
export const USER_NEWSLETTER_UPDATE_FAIL = "USER_NEWSLETTER_UPDATE_FAIL"
