  export default [
    { value: "Acireale", label: "Acireale" },
    { value: "Ancona", label: "Ancona"},
    { value: "Alba Adriatica", label: "Alba Adriatica" },
    { value: "Alessandria", label: "Alessandria" },
    { value: "Arezzo", label: "Arezzo" },
    { value: "Asti", label: "Asti"},
    { value: "Belluno", label: "Belluno" },
    { value: "Bologna", label: "Bologna" },
    { value: "Bolzano", label: "Bolzano" },
    { value: "Cuneo", label: "Cuneo" },
    { value: "Cremona", label: "Cremona" },
    { value: "Torino", label: "Torino" },
    { value: "Vercelli", label: "Vercelli" },
    { value: "Novara", label: "Novara" },
    { value: "Biella", label: "Biella" },
    { value: "Verbano-Cusio,-Ossola", label: "Verbano-Cusio,-Ossola" },
    { value: "Valle d'Aosta", label: "Valle d'Aosta" },
    { value: "Varese", label: "Varese" },
    { value: "Como", label: "Como" },
    { value: "Sondrio", label: "Sondrio" },
    { value: "Milano", label: "Milano" },
    { value: "Bergamo", label: "Bergamo" },
    { value: "Brescia", label: "Brescia" },
    { value: "Pavia", label: "Pavia" },
    { value: "Mantova", label: "Mantova" },
    { value: "Lecco", label: "Lecco" },
    { value: "Lodi", label: "Lodi" },
    { value: "Monza e della Brianza", label: "Monza e della Brianza" },
    { value: "Trento", label: "Trento" },
    { value: "Verona", label: "Verona" },
    { value: "Vicenza", label: "Vicenza" },
    { value: "Treviso", label: "Treviso" },
    { value: "Venezia", label: "Venezia" },
    { value: "Rovigo", label: "Rovigo" },
    { value: "Udine", label: "Udine" },
    { value: "Gorizia", label: "Gorizia" },
    { value: "Trieste", label: "Trieste" },
    { value: "Pordenone", label: "Pordenone" },
    { value: "Imperia", label: "Imperia" },
    { value: "Savona", label: "Savona" },
    { value: "Genova", label: "Genova" },
    { value: "La Spezia", label: "La Spezia" },
    { value: "Piacenza", label: "Piacenza" },
    { value: "Parma", label: "Parma" },
    { value: "Reggio nell'Emilia", label: "Reggio nell'Emilia" },
    { value: "Modena", label: "Modena" },
    { value: "Ferrara", label: "Ferrara" },
    { value: "Ravenna", label: "Ravenna" },
    { value: "Forlì-Cesena", label: "Forlì-Cesena" },
    { value: "Rimini", label: "Rimini" },
    { value: "Massa-Carrara", label: "Massa-Carrara" },
    { value: "Lucca", label: "Lucca" },
    { value: "Pistoia", label: "Pistoia" },
    { value: "Firenze", label: "Firenze" },
    { value: "Livorno", label: "Livorno" },
    { value: "Pisa", label: "Pisa" },
    { value: "Siena", label: "Siena" },
    { value: "Grosseto", label: "Grosseto" },
    { value: "Prato", label: "Prato" },
    { value: "Perugia", label: "Perugia" },
    { value: "Terni", label: "Terni" },
    { value: "Pesaro e Urbino", label: "Pesaro e Urbino" },
    { value: "Macerata", label: "Macerata" },
    { value: "Ascoli Piceno", label: "Ascoli Piceno" },
    { value: "Fermo", label: "Fermo" },
    { value: "Viterbo", label: "Viterbo" },
    { value: "Rieti", label: "Rieti" },
    { value: "Roma", label: "Roma" },
    { value: "Latina", label: "Latina" },
    { value: "Frosinone", label: "Frosinone" },
    { value: "L'Aquila", label: "L'Aquila" },
    { value: "Teramo", label: "Teramo" },
    { value: "Pescara", label: "Pescara" },
    { value: "Chieti", label: "Chieti" },
    { value: "Campobasso", label: "Campobasso" },
    { value: "Isernia", label: "Isernia" },
    { value: "Caserta", label: "Caserta" },
    { value: "Benevento", label: "Benevento" },
    { value: "Napoli", label: "Napoli" },
    { value: "Avellino", label: "Avellino" },
    { value: "Salerno", label: "Salerno" },
    { value: "Foggia", label: "Foggia" },
    { value: "Bari", label: "Bari" },
    { value: "Taranto", label: "Taranto" },
    { value: "Brindisi", label: "Brindisi" },
    { value: "Lecce", label: "Lecce" },
    { value: "Barletta-Andria-Trani", label: "Barletta-Andria-Trani" },
    { value: "Potenza", label: "Potenza" },
    { value: "Matera", label: "Matera" },
    { value: "Cosenza", label: "Cosenza" },
    { value: "Catanzaro", label: "Catanzaro" },
    { value: "Reggio Calabria", label: "Reggio Calabria" },
    { value: "Crotone", label: "Crotone" },
    { value: "Vibo Valentia", label: "Vibo Valentia" },
    { value: "Trapani", label: "Trapani" },
    { value: "Palermo", label: "Palermo" },
    { value: "Messina", label: "Messina" },
    { value: "Agrigento", label: "Agrigento" },
    { value: "Caltanissetta", label: "Caltanissetta" },
    { value: "Enna", label: "Enna" },
    { value: "Catania", label: "Catania" },
    { value: "Ragusa", label: "Ragusa" },
    { value: "Siracusa", label: "Siracusa" },
    { value: "Sassari", label: "Sassari" },
    { value: "Nuoro", label: "Nuoro" },
    { value: "Cagliari", label: "Cagliari" },
    { value: "Oristano", label: "Oristano" },
    { value: "Sud Sardegna", label: "Sud Sardegna" },
  ]